"""Add description status opportunity_id to team

Revision ID: aabbd5343f3e
Revises: add_company_contact
Create Date: 2026-02-06 01:17:03.772940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabbd5343f3e'
down_revision: Union[str, None] = 'add_company_contact'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('team', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('team', sa.Column('opportunity_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'team', 'opportunity', ['opportunity_id'], ['opportunity_id'], ondelete='CASCADE')
    op.add_column('team_opening', sa.Column('role_title', sa.String(length=100), nullable=False))
    op.add_column('team_opening', sa.Column('total_slots', sa.Integer(), nullable=False))
    op.add_column('team_opening', sa.Column('filled_slots', sa.Integer(), nullable=False))
    op.add_column('team_opening', sa.Column('tags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_opening', 'tags')
    op.drop_column('team_opening', 'filled_slots')
    op.drop_column('team_opening', 'total_slots')
    op.drop_column('team_opening', 'role_title')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'opportunity_id')
    op.drop_column('team', 'status')
    op.drop_column('team', 'description')
    # ### end Alembic commands ###
