"""Add team_invitation table

Revision ID: 0b8f987b6dcc
Revises: aabbd5343f3e
Create Date: 2026-02-06 02:17:14.005932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8f987b6dcc'
down_revision: Union[str, None] = 'aabbd5343f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invitation',
    sa.Column('invitation_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('inviter_student_id', sa.String(length=50), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('invitee_student_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_invitation')
    # ### end Alembic commands ###
