"""Add profile_photo_url to user table

Revision ID: 6e9ce5932239
Revises: 0b8f987b6dcc
Create Date: 2026-02-06 02:31:14.029575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9ce5932239'
down_revision: Union[str, None] = '0b8f987b6dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_photo_url')
    # ### end Alembic commands ###
