"""Initial migration

Revision ID: 9e7e1103977e
Revises: 428d992b2fc1
Create Date: 2026-01-29 02:42:06.758003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7e1103977e'
down_revision: Union[str, None] = '428d992b2fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_task',
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('task_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('task_code')
    )
    op.create_table('badge',
    sa.Column('badge_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('match_result',
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('source_entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_entity_id', sa.String(length=50), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('opportunity',
    sa.Column('opportunity_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by_type', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_table('tag',
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('ai_prompt',
    sa.Column('prompt_id', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ai_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('badge_assignment',
    sa.Column('badge_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.badge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('badge_id', 'entity_type', 'entity_id')
    )
    op.create_table('company',
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('professor',
    sa.Column('professor_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('research_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('social_link',
    sa.Column('social_link', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('social_link')
    )
    op.create_table('student',
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('degree_level', sa.String(length=100), nullable=True),
    sa.Column('Email_Address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tag_assignment',
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'entity_type', 'entity_id')
    )
    op.create_table('ai_analysis',
    sa.Column('analysis_id', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('prompt_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=255), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompt.prompt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['ai_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('certificate',
    sa.Column('certificate_id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('certificate_name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('obtained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    op.create_table('cv',
    sa.Column('cv_id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cv_id')
    )
    op.create_table('project',
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('repo_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by_student_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_student_id'], ['student.student_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('application',
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('opportunity_id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('team_member',
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'student_id')
    )
    op.create_table('team_opening',
    sa.Column('opening_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('query_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opening_id')
    )
    op.create_table('team_application',
    sa.Column('team_app_id', sa.String(length=50), nullable=False),
    sa.Column('team_opening_id', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('applicant_student_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_opening_id'], ['team_opening.opening_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('team_app_id')
    )
    op.create_table('join_request_vote',
    sa.Column('vote_id', sa.String(length=50), nullable=False),
    sa.Column('team_app_id', sa.String(length=50), nullable=False),
    sa.Column('voter_student_id', sa.String(length=50), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_app_id'], ['team_application.team_app_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_request_vote')
    op.drop_table('team_application')
    op.drop_table('team_opening')
    op.drop_table('team_member')
    op.drop_table('application')
    op.drop_table('team')
    op.drop_table('project')
    op.drop_table('cv')
    op.drop_table('certificate')
    op.drop_table('ai_analysis')
    op.drop_table('tag_assignment')
    op.drop_table('student')
    op.drop_table('social_link')
    op.drop_table('professor')
    op.drop_table('company')
    op.drop_table('badge_assignment')
    op.drop_table('ai_prompt')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('opportunity')
    op.drop_table('match_result')
    op.drop_table('badge')
    op.drop_table('ai_task')
    # ### end Alembic commands ###
